import type { Direction } from "./prompt";

/**
 * Professionally curated starting points. Each preset is a complete recipe of
 * control values (the user's subject and environment are preserved when one is
 * applied). Reusable by any future image workflow that consumes a Direction.
 */
export type Preset = {
  id: string;
  name: string;
  descriptor: string;
  values: Partial<Direction>;
};

export const presets: Preset[] = [
  {
    id: "luxury-product",
    name: "Luxury Product Photography",
    descriptor: "Quiet, expensive, immaculate surface",
    values: {
      category: "luxury-product",
      style: "luxe",
      mood: "refined",
      lighting: "softbox",
      composition: "negative",
      colorGrade: "neutral",
      camera: "phaseone",
      lens: "100",
      aperture: "8",
      material: "marble",
      texture: "matte",
      render: "studio-render",
      quality: "ultra",
      aspect: "4-5",
    },
  },
  {
    id: "beauty-campaign",
    name: "Beauty Campaign",
    descriptor: "Dewy skin, clean light, glossy finish",
    values: {
      category: "beauty",
      style: "editorial",
      mood: "refined",
      lighting: "softbox",
      composition: "centered",
      colorGrade: "cool-editorial",
      camera: "canon",
      lens: "85",
      aperture: "2",
      texture: "glossy",
      render: "editorial-print",
      quality: "ultra",
      aspect: "4-5",
    },
  },
  {
    id: "fashion-editorial",
    name: "Fashion Editorial",
    descriptor: "Attitude, movement, hard light",
    values: {
      category: "fashion",
      style: "editorial",
      mood: "bold",
      lighting: "hard-sun",
      composition: "thirds",
      colorGrade: "rich",
      camera: "sony",
      lens: "85",
      aperture: "2.8",
      render: "editorial-print",
      aspect: "2-3",
    },
  },
  {
    id: "ugc",
    name: "UGC",
    descriptor: "Handheld, honest, vertical",
    values: {
      category: "ugc",
      style: "documentary",
      mood: "playful",
      lighting: "window",
      composition: "centered",
      colorGrade: "neutral",
      camera: "sony",
      lens: "35",
      aperture: "2.8",
      render: "photographic",
      aspect: "9-16",
    },
  },
  {
    id: "lifestyle",
    name: "Lifestyle",
    descriptor: "In the moment, warm morning",
    values: {
      category: "lifestyle",
      style: "documentary",
      mood: "serene",
      lighting: "window",
      composition: "thirds",
      colorGrade: "warm-film",
      camera: "canon",
      lens: "35",
      aperture: "2",
      timeOfDay: "morning",
      aspect: "4-5",
    },
  },
  {
    id: "flat-lay",
    name: "Flat Lay",
    descriptor: "Top-down, arranged, even light",
    values: {
      category: "flat-lay",
      style: "minimal",
      mood: "refined",
      lighting: "softbox",
      composition: "overhead",
      colorGrade: "neutral",
      camera: "hasselblad",
      lens: "50",
      aperture: "8",
      material: "paper",
      texture: "matte",
      aspect: "1-1",
    },
  },
  {
    id: "food",
    name: "Food Photography",
    descriptor: "Appetite, side light, close",
    values: {
      category: "food",
      style: "editorial",
      mood: "intimate",
      lighting: "window",
      composition: "closeup",
      colorGrade: "warm-film",
      camera: "canon",
      lens: "100",
      aperture: "2.8",
      texture: "glossy",
      aspect: "4-5",
    },
  },
  {
    id: "architecture",
    name: "Architecture",
    descriptor: "Line, concrete, hard midday sun",
    values: {
      category: "architecture",
      style: "minimal",
      mood: "bold",
      lighting: "hard-sun",
      composition: "leading",
      colorGrade: "cool-editorial",
      camera: "sony",
      lens: "24",
      aperture: "11",
      material: "concrete",
      timeOfDay: "midday",
      weather: "clear",
      aspect: "3-2",
    },
  },
  {
    id: "interior",
    name: "Interior Design",
    descriptor: "Warm wood, symmetry, golden light",
    values: {
      category: "interior",
      style: "editorial",
      mood: "serene",
      lighting: "window",
      composition: "symmetry",
      colorGrade: "warm-film",
      camera: "sony",
      lens: "24",
      aperture: "5.6",
      material: "wood",
      timeOfDay: "golden",
      aspect: "3-2",
    },
  },
  {
    id: "travel",
    name: "Travel",
    descriptor: "Golden hour, place, atmosphere",
    values: {
      category: "travel",
      style: "cinematic",
      mood: "nostalgic",
      lighting: "golden",
      composition: "leading",
      colorGrade: "teal-orange",
      camera: "leica",
      lens: "35",
      aperture: "5.6",
      timeOfDay: "golden",
      weather: "clear",
      aspect: "3-2",
    },
  },
  {
    id: "automotive",
    name: "Automotive",
    descriptor: "Wet asphalt, rim light, blue hour",
    values: {
      category: "automotive",
      style: "cinematic",
      mood: "bold",
      lighting: "rim",
      composition: "low-angle",
      colorGrade: "teal-orange",
      camera: "sony",
      lens: "35",
      aperture: "5.6",
      material: "metal",
      weather: "rain",
      timeOfDay: "blue",
      aspect: "16-9",
    },
  },
  {
    id: "jewelry",
    name: "Jewelry",
    descriptor: "Macro sparkle, deep focus, studio",
    values: {
      category: "luxury-product",
      style: "luxe",
      mood: "refined",
      lighting: "softbox",
      composition: "closeup",
      colorGrade: "neutral",
      camera: "phaseone",
      lens: "100",
      aperture: "11",
      material: "metal",
      texture: "glossy",
      render: "studio-render",
      quality: "ultra",
      aspect: "1-1",
    },
  },
  {
    id: "watches",
    name: "Watches",
    descriptor: "Rim-lit metal, cool grade, macro",
    values: {
      category: "luxury-product",
      style: "luxe",
      mood: "refined",
      lighting: "rim",
      composition: "closeup",
      colorGrade: "cool-editorial",
      camera: "phaseone",
      lens: "100",
      aperture: "11",
      material: "metal",
      texture: "glossy",
      render: "studio-render",
      quality: "ultra",
      aspect: "1-1",
    },
  },
  {
    id: "cosmetics",
    name: "Cosmetics",
    descriptor: "Glass, pastel grade, soft studio",
    values: {
      category: "beauty",
      style: "minimal",
      mood: "refined",
      lighting: "softbox",
      composition: "centered",
      colorGrade: "pastel",
      camera: "canon",
      lens: "100",
      aperture: "8",
      material: "glass",
      texture: "glossy",
      aspect: "4-5",
    },
  },
  {
    id: "cinematic-portrait",
    name: "Cinematic Portrait",
    descriptor: "Rembrandt key, shallow, filmic",
    values: {
      category: "portrait",
      style: "cinematic",
      mood: "mysterious",
      lighting: "rembrandt",
      composition: "closeup",
      colorGrade: "teal-orange",
      camera: "sony",
      lens: "85",
      aperture: "1.4",
      render: "cinematic-film",
      aspect: "2-3",
    },
  },
  {
    id: "street",
    name: "Street Photography",
    descriptor: "Analog grain, mixed light, night",
    values: {
      category: "lifestyle",
      style: "documentary",
      mood: "energetic",
      lighting: "mixed",
      composition: "thirds",
      colorGrade: "faded",
      camera: "leica",
      lens: "35",
      aperture: "5.6",
      texture: "grain",
      render: "analog",
      timeOfDay: "night",
      aspect: "3-2",
    },
  },
  {
    id: "minimalist",
    name: "Minimalist",
    descriptor: "Negative space, matte paper, calm",
    values: {
      category: "luxury-product",
      style: "minimal",
      mood: "serene",
      lighting: "softbox",
      composition: "negative",
      colorGrade: "neutral",
      camera: "hasselblad",
      lens: "50",
      aperture: "5.6",
      material: "paper",
      texture: "matte",
      aspect: "4-5",
    },
  },
  {
    id: "scandinavian",
    name: "Scandinavian",
    descriptor: "Pale wood, overcast, airy",
    values: {
      category: "interior",
      style: "minimal",
      mood: "serene",
      lighting: "window",
      composition: "negative",
      colorGrade: "neutral",
      camera: "sony",
      lens: "35",
      aperture: "2.8",
      material: "wood",
      timeOfDay: "morning",
      weather: "overcast",
      aspect: "4-5",
    },
  },
  {
    id: "dark-luxury",
    name: "Dark Luxury",
    descriptor: "Velvet shadow, rich grade, low key",
    values: {
      category: "luxury-product",
      style: "luxe",
      mood: "mysterious",
      lighting: "rembrandt",
      composition: "negative",
      colorGrade: "rich",
      camera: "phaseone",
      lens: "100",
      aperture: "8",
      material: "velvet",
      texture: "matte",
      render: "studio-render",
      quality: "ultra",
      aspect: "4-5",
    },
  },
  {
    id: "editorial-magazine",
    name: "Editorial Magazine",
    descriptor: "Cover-ready, cool grade, print",
    values: {
      category: "fashion",
      style: "editorial",
      mood: "bold",
      lighting: "softbox",
      composition: "thirds",
      colorGrade: "cool-editorial",
      camera: "hasselblad",
      lens: "50",
      aperture: "5.6",
      render: "editorial-print",
      quality: "ultra",
      aspect: "2-3",
    },
  },
];
